version: '3'

services:
  # Node.js application
  app:
    build: ./
    mem_limit: 512m
    working_dir: /app
    environment:
      NODE_ENV: test
      EMAIL_PROVIDER: gmail # Set if necessary.
      EMAIL_USERNAME: <set your email username>
      EMAIL_PASSWORD: <set your email password>
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db

  # MySQL database
  db:
    image: mysql:8
    mem_limit: 512m
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: db_development
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data:
